POST http://localhost:8080/actuator/chaosmonkey/assaults
Content-Type: application/json

{
  "cpuActive": false,
  "cpuMillisecondsHoldLoad": 90000,
  "cpuLoadTargetFraction": 0.9,
  "cpuCronExpression": "OFF"
}
