POST http://localhost:8080/actuator/chaosmonkey/assaults
Content-Type: application/json

{
  "level": 1,
  "exceptionsActive": true,
  "exception": {
    "type": "java.lang.RuntimeException",
    "arguments": null
  }
}
