POST http://localhost:8080/actuator/chaosmonkey/assaults
Content-Type: application/json

{
  "memoryActive": true,
  "memoryMillisecondsHoldFilledMemory": 90000,
  "memoryMillisecondsWaitNextIncrease": 1000,
  "memoryFillIncrementFraction": 0.15,
  "memoryFillTargetFraction": 0.25
}